# local setup of an s3 replica for local testing

services:
  s3:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
      - S3_BUCKET=${S3_BUCKET:-locals3}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-test}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-test}
    volumes:
      - "./s3_local/init_s3.py:/etc/localstack/init/ready.d/init-s3.py"
      - "./s3_local/data:/var/lib/localstack"
